# Generated by Django 5.0.1 on 2024-01-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchinglog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='観戦日')),
                ('home', models.CharField(max_length=30, verbose_name='ホーム')),
                ('visiter', models.CharField(max_length=30, verbose_name='ビジター')),
                ('stadium', models.CharField(max_length=30, verbose_name='球場')),
                ('home_score', models.PositiveIntegerField(verbose_name='ホームチーム得点')),
                ('visiter_score', models.PositiveIntegerField(verbose_name='ビジターチーム得点')),
                ('memo', models.TextField(blank=True, verbose_name='感想')),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
